openapi: 3.0.0
info:
  title: КОЛЛЕДЖИ.РФ Backend API V1
  version: 1.0.0
servers:
  - url: http://localhost:8000/
    description: local
  - url: https://develop-4184.c4.syndev.ru/
    description: develop

tags: $tags

paths: $paths

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters: $parameters
  requestBodies: $requestBodies
  responses: $responses
  schemas: $schemas
