openapi: 3.0.0
info:
  title: $title
  version: $version
  description: $description
servers: $servers

tags: $tags

paths: $paths

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters: $parameters
  requestBodies: $requestBodies
  responses: $responses
  schemas: $schemas
