query:
  $nameComponent:
    in: query
    name: filter[{$key}]
    description: $description
    schema:
      type: $type
      example: $example
enum:
  $nameComponent:
    in: query
    name: $key
    description: $description
    explode: false
    schema:
      type: array
      items:
        type: string
        enum: $enum

simple.enum:
  $nameComponent:
    in: query
    name: filter[{$key}]
    description: $description
    schema:
      type: string
      enum: $enum

fields:
  $nameComponent:
    in: query
    name: fields[{$type}]
    description: $description
    schema:
      type: string
      example: $example
